# Generated by Django 5.1.2 on 2024-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
