# Generated by Django 5.1.2 on 2024-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_capa_alter_blog_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subnome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
